run:
  # Default timeout is 1m, up to give more room
  timeout: 4m

linters:
  enable:
  - asciicheck
  - deadcode
  - depguard
  - errorlint
  - gofmt
  - goimports
  - importas
  - prealloc
  - nestif
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace

linters-settings:
  importas:
    alias:
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: apierrors
    - pkg: github.com/operator-framework/api/pkg/operators/v1alpha1
      alias: operatorsv1alpha1
    - pkg: github.com/openshift/api/platform/v1alpha1
      alias: platformv1alpha1
    - pkg: github.com/openshift/platform-operators/api/v1alpha1
      alias: platformtypes
  revive:
    rules:
    - name: dot-imports
      severity: warning
      disabled: true
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/gomega
      - github.com/onsi/ginkgo
  goimports:
    local-prefixes: github.com/openshift/platform-operators,github.com/openshift/api/platform/v1alpha1

output:
  format: tab
