apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: aggregated
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
