apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
    service.beta.openshift.io/inject-cabundle: "true"
  name: platform-operators-rukpak-webhook-tls
  namespace: openshift-platform-operators
