apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: platform-operators-controller-manager
  namespace: openshift-platform-operators
