apiVersion: v1
kind: Namespace
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  labels:
    control-plane: controller-manager
  name: openshift-platform-operators
