apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-rukpak-webhooks-admin
  namespace: openshift-platform-operators
