apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  labels:
    control-plane: controller-manager
  name: platform-operators-controller-manager-metrics-service
  namespace: openshift-platform-operators
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
