apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-controller-manager
  namespace: openshift-platform-operators
