apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  labels:
    control-plane: controller-manager
  name: openshift-platform-operators
