apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
    service.beta.openshift.io/serving-cert-secret-name: platform-operators-rukpak-core-tls
  name: platform-operators-rukpak-core
  namespace: openshift-platform-operators
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: core
