apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-controller-manager
  namespace: openshift-platform-operators
